language: rust

env:
  global:
    - secure: e4pa7H95ZfXleM2lRNlzVIR8vVJS0sPfsu4bahK6UG7ycPE6nZvkO4+zTGQn8/58f49y+MOSjIDjM+YjlfIWjAYX5WRnWooSu1DpDGaOYPIrAJ+RYibidPlFXKBxnl9KIjcy2Oa0/o3HhBfQ4zlR2/rGyQePFL8xmgsGXKOjyWY=

script:
    - cargo build -v
    - cargo test -v

after_script:
  - cargo doc -v
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
